FROM mauricioroberto/lugo4php:8.3.11

WORKDIR /app

# COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY composer.json composer.lock ./

COPY src ./src

RUN composer install --no-dev

RUN composer dump-autoload --optimize

CMD [ "php", "src/main.php" ]
